kind: pipeline
type: exec
name: default

clone:
  depth: 1

concurrency:
  limit: 1

trigger:
  branch:
    - main
    - master
  event:
    - push
  ref:
    - refs/heads/master

steps:
  - name: "build"
    commands:
      - docker build -f dockerfiles/demo -t lumenswap-front:${DRONE_COMMIT_SHA:0:7} .
  - name: "Package"
    environment:
      MANIFEST_PATH:
        from_secret: MANIFEST_PATH
      PACKAGE_PATH:
        from_secret: PACKAGE_PATH
    commands:
      - helm package --app-version ${DRONE_COMMIT_SHA:0:7}  $MANIFEST_PATH/lumenswap-demo -d $PACKAGE_PATH/lumenswap-demo
      - mv $PACKAGE_PATH/lumenswap-demo/lumenswap-demo-0.1.0.tgz $PACKAGE_PATH/lumenswap-demo/lumenswap-demo-${DRONE_COMMIT_SHA:0:7}.tgz
    depends_on:
      - build
  - name: deploy-demo
    environment:
      PACKAGE_PATH:
        from_secret: PACKAGE_PATH
      CONFIG_PATH:
        from_secret: CONFIG_PATH
    commands:
      - export KUBECONFIG=$CONFIG_PATH/kube_config
      - helm upgrade lumenswap-demo $PACKAGE_PATH/lumenswap-demo/lumenswap-demo-${DRONE_COMMIT_SHA:0:7}.tgz --namespace lumenswap-demo --wait --atomic --install
    depends_on:
      - build
      - Package

---
kind: pipeline
type: exec
name: production

clone:
  depth: 1

concurrency:
  limit: 1

trigger:
  branch:
    - main
    - master
  event:
    - promote
  target:
    - production
  ref:
    - refs/heads/master

steps:
  - name: "build"
    commands:
      - docker build -f dockerfiles/$product -t lumenswap-front-$product:${DRONE_COMMIT_SHA:0:7} .
  - name: "Package"
    environment:
      MANIFEST_PATH:
        from_secret: MANIFEST_PATH
      PACKAGE_PATH:
        from_secret: PACKAGE_PATH
    commands:
      - helm package --app-version ${DRONE_COMMIT_SHA:0:7}  $MANIFEST_PATH/lumenswap-front-$product -d $PACKAGE_PATH/lumenswap-front-$product
      - mv $PACKAGE_PATH/lumenswap-front-$product/lumenswap-front-$product-0.1.0.tgz $PACKAGE_PATH/lumenswap-front-$product/lumenswap-front-$product-${DRONE_COMMIT_SHA:0:7}.tgz

    depends_on:
      - build
  - name: deploy-prod
    environment:
      PACKAGE_PATH:
        from_secret: PACKAGE_PATH
      CONFIG_PATH:
        from_secret: CONFIG_PATH
    commands:
      - export KUBECONFIG=$CONFIG_PATH/kube_config
      - helm upgrade lumenswap-front-$product $PACKAGE_PATH/lumenswap-front-$product/lumenswap-front-$product-${DRONE_COMMIT_SHA:0:7}.tgz --namespace lumenswap-prod --wait --atomic --install
    depends_on:
      - build
      - Package



# ---
# kind: pipeline
# type: exec
# name: production

# clone:
#   disable: true

# concurrency:
#   limit: 1

# trigger:
#   branch:
#     - main
#     - master
#   event:
#     - rollback
#   target:
#     - production
#   ref:
#     - refs/heads/master

# steps:
#   - name: rollback
#     environment:  
#       CONFIG_PATH:
#         from_secret: CONFIG_PATH
#     commands:
#       - export KUBECONFIG=$CONFIG_PATH/kube_config
#       - helm rollback lumenswap-demo -n lumenswap-demo $(helm history lumenswap-demo -n lumenswap-demo | grep $tag | awk '{print $1}') --wait --dry-run
#     depends_on:
#       - build
#       - Package


