variables:
  imageTag: lumenswap-front:$CI_COMMIT_SHORT_SHA

stages:
  - build

build and generate docker image:
  stage: build
  script:
    - export KUBECONFIG=$MANIFEST_HOME/config
    - docker build -t $imageTag .
    - helm upgrade $MANIFEST_HOME/manifest/lumenswap-front -n lumenswap-prod --set-image.tag=$CI_COMMIT_SHORT_SHA --wait --install --atomic
