variables:
  imageTag: lumenswap-front:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy-demo
  - deploy-prod

build:
  only:
    - master
  stage: build
  script:
    - docker build -t $imageTag .
  tags:
    - runner


deploy to demo:
  only:
    - master
  stage: deploy-demo
  script:
    - export KUBECONFIG=$MANIFEST_HOME/../config
    - helm upgrade lumenswap-demo $MANIFEST_HOME/lumenswap-demo --set image.tag=$CI_COMMIT_SHORT_SHA  --namespace lumenswap-demo --wait --atomic --install
  tags:
    - runner


deploy to prod:
  only:
    - master
  stage: deploy-prod
  when: manual
  script:
    - export KUBECONFIG=$MANIFEST_HOME/../config
    - helm upgrade lumenswap-front $MANIFEST_HOME/lumenswap-front --set image.tag=$CI_COMMIT_SHORT_SHA --namespace lumenswap-prod --wait --atomic --install
  tags:
    - runner